import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import dynamic from "next/dynamic";
import SSE from "./SSE";

// const SSE = dynamic(() => import("./SSE"), {
//   ssr: false,
// });

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SSE />
        {children}
      </body>
    </html>
  );
}
